# Site Settings
title: Chris Wininger -- Full Stack Developer
url: 'https://www.chriswininger.com'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Chris Wininger
tagline: Full Stack Developer
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Christopher Wininger has a decade of experience developing software solutions. He enjoys learning and is constantly seeking to improve his process by evaluating the newest technologies and methods for application design. He flourishes in a team setting and has experience working with large code bases through the duration of the software life cycle. Christopher greatly values well managed, maintainable code. He strives to bring consistency and a well planned structure to all of his projects.'

#sidebar links
email: chris.wininger@gmail.com
#phone: 012 345 6789
website: www.wegotrats.com #do not add http://
linkedin: christopher-wininger-dev
github: chriswininger
twitter: '@remembersonly'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# exclude:
#    - Gemfile
#    - Gemfile.lock
#    - node_modules
#    - vendor/bundle/
#    - vendor/cache/
#    - vendor/gems/
#    - vendor/ruby/

